### ISSUE TITLE
Add-DfsrMember

### ISSUE THREAD

**Issue by markatdxb** [dsccommunity/DFSDsc#128]
Hello just got a short questions, hope you can help me here.
I have existing Replication group up with multiple members, just wondering which resource should I use to add additional DFSR member ? 
Im bit lost with the modules funcionality
thanks

**Comment by johlju** [comment]
Maybe this example helps? https://github.com/dsccommunity/DFSDsc/blob/main/source/Examples/Resources/DFSReplicationGroupMembership/2-DFSReplicationGroupMembership_Complete_Config.ps1

**Comment by markatdxb** [comment]
@johlju im actually curious about this part. This example shows the initial setup with 2 replication group members. In case i would like to add another member(s) to the replication group, i dont see option to ADD member. Should I assume that i would need to re-run below and code specify all 3 members ( existing ones and the new one )?

```
# Configure the Replication Group
        DFSReplicationGroup RGPublic
        {
            GroupName = 'Public'
            Description = 'Public files for use by all departments'
            Ensure = 'Present'
            Members = 'FileServer1.contoso.com','FileServer2.contoso.com'
            Folders = 'Software'
            PSDSCRunAsCredential = $Credential
            DependsOn = '[WindowsFeature]RSATDFSMgmtConInstall'
        } # End of RGPublic Resource
```

**Comment by PlagueHO** [comment]
Hi @markatdxb, sorry I didn't post earlier. With this resource, you're not providing instructions on how to get the group into state, rather you're defining the desired state and the resource will figure out what members to add/remove to do that.

So, you should just set the Members to whatever the complete list of members you want to have in the group. If any are missing, they'll be added. Does that make sense?

V5.0 of this resource is also about to be released and will have additional control, but it will still be about defining the desired state, not "changes" to the state.

**Comment by markatdxb** [comment]
Thanks for clarification. Conceptually it makes sense. The only issue in the scenario is that I need to know the names of existing members in order to be able to add the new one. Some other collections provide info modules to get existing configuration. Any plans here to do the same for DFS ?

**Comment by Borgquite** [comment]
@markatdxb I believe once 5.0.0 is released you should be able to achieve what you want by:

- Leaving the DFSReplicationGroup Members parameter **undefined**
- Using the new DFSReplicationGroupMember resource to add a new member (this will not affect existing ones)

Hope this helps - example config here: https://github.com/dsccommunity/DFSDsc/blob/main/source/Examples/Resources/DFSReplicationGroupMember/1-DFSReplicationGroupMember_Simple_Config.ps1

**Comment by PlagueHO** [comment]
We will release v5.0.0 final as soon as the publish wiki issue is fixed.

**Comment by PlagueHO** [comment]
v5.0.0 has been published now. Can you confirm that it has resolved this issue?

**Comment by markatdxb** [comment]
Tested and workes as expected !!! thanks
