### ISSUE TITLE
Azure Pipelines status showing as 'failed'; latest build returns 'Pipeline not found'

### ISSUE THREAD

**Issue by Borgquite** [dsccommunity/DFSDsc#130]
This really is a nit pick - blame @johlju for encouraging me to report things in #129 :)

For some reason on the front page the 'Azure Pipelines' build status shows as 'FAILED':

![image](https://github.com/dsccommunity/DFSDsc/assets/53898223/39402571-505d-408a-8ade-6c4e021cbbd8)

Clicking this returns the results for a (failed) 4.5.0-preview.2 build.

![image](https://github.com/dsccommunity/DFSDsc/assets/53898223/d4831fb3-ab78-42e8-b458-23a9e1e0e728)

From there clicking 'Pipelines' shows the successful 5.0.0 build:

![image](https://github.com/dsccommunity/DFSDsc/assets/53898223/a6e859a4-ee85-40ed-b93c-49a06a2202b1)

But clicking that link for more details shows 'Pipeline not found':

![image](https://github.com/dsccommunity/DFSDsc/assets/53898223/4720ac55-2a15-4844-bb16-981ef02b14e4)

Not a big deal but seems the automated build process is still a bit 'off'

**Comment by johlju** [comment]
Hmm, that was a new one. Thanks again for reporting, learn new stuff. 🙂 This probably because as per #129 several pipelines ran on the same commit ID. Guessing it find a random job and reports that, not sure if it possible to fix without pushing a new commit and then releasing that commit as 5.0.1 or something. 🤔

**Comment by johlju** [comment]
It gets the badge from this URL: https://dev.azure.com/dsccommunity/DFSDsc/_apis/build/status/dsccommunity.DFSDsc?branchName=main

The API has no options to choose "the last one": https://learn.microsoft.com/en-us/rest/api/azure/devops/build/status/get?view=azure-devops-rest-7.0

**Comment by johlju** [comment]
So if we can find a typo or something else easy to fix under the source folder, then we can release a patch version and hopefully the label will be green (it works in other repos, when there is a single release on one commit ID). 😉

**Comment by johlju** [comment]
This file should no longer be needed with the latest ModuleBuilder version, so it is safe to remove: https://github.com/dsccommunity/DFSDsc/blob/main/source/Build.psd1

**Comment by johlju** [comment]
@Borgquite if you would be so kind to review (sign off) on the PR https://github.com/dsccommunity/DFSDsc/pull/131 then I can merge it (once the tests passes).

**Comment by Borgquite** [comment]
@johlju :) Don't have write access so not sure if my review is enough. Nonetheless have done so in case it helps! :)

**Comment by johlju** [comment]
Should be all good now. 🙂
