### ISSUE TITLE
Full release of 5.1.0

### ISSUE THREAD

**Issue by Borgquite** [dsccommunity/DFSDsc#136]
Hi,

Version v5.1.0-preview002 has been out for a little while & seems OK - please can we have a full release?

Many thanks,
Chris

**Comment by johlju** [comment]
Been on my todo list for a while, just haven't gotten around to it due to work and family commitments. 🙂  I will do it as soon as I have time.

**Comment by johlju** [comment]
It will be released shortly. I pushed a new full release tag.

**Comment by Borgquite** [comment]
@johlju Family first! Thanks so much, really appreciate this :)
