### ISSUE TITLE
Full release of 5.1.1

### ISSUE THREAD

**Issue by Borgquite** [dsccommunity/DFSDsc#139]
Hi @PlagueHO Just tested the 5.1.1-preview0001 release with #58 fix and all looks OK from here.

Whenever you're ready, would be great to have full release :)

Many thanks!
Chris

**Comment by PlagueHO** [comment]
On the way, thanks for submitting and testing @Borgquite !

**Comment by PlagueHO** [comment]
Done! https://www.powershellgallery.com/packages/DFSDsc/5.1.1
