### ISSUE TITLE
unable to create domain dfs root

### ISSUE THREAD

**Issue by joeypiccola** [dsccommunity/DFSDsc#23]
Been trying to figure this one out. At first I thought it was a dependency on the TargetPath file share, but I've created that and I still get the error below. I can get this to work when manually running New-DfsnRoot. 

**DFS dsc verbose**
![image](https://cloud.githubusercontent.com/assets/8612198/19711441/f286a89a-9af2-11e6-97c3-66526342adc5.png)

**manual run new-dfsnroot works**
![image](https://cloud.githubusercontent.com/assets/8612198/19711460/18482874-9af3-11e6-8305-c3dfc3e3f64c.png)

**dfs.ps1 script**

```
Configuration DFSNamespace_Domain_SingleTarget
{

    Import-DscResource -ModuleName 'xDFS'
    Import-DscResource -ModuleName 'xSMBShare'
    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

    Node $allnodes.nodename
    {

        File DFSRootDirectory 
        {
            Ensure          = "Present"
            DestinationPath = "c:\DFSRoots\Files"
            Type            = "Directory"
        }

        xSMBShare DFSRootShare
        {
            DependsOn  = "[File]DFSRootDirectory"
            Name       = "Files"
            FullAccess = "ad\domain admins"
            ReadAccess = "Everyone"
            Path       = "C:\DFSRoots\Files"
            Ensure     = "Present"
        }

        WindowsFeature DFSFileServices
        {
            Name   = "FS-DFS-Namespace"
            Ensure = "Present"
        } 

        WindowsFeature RSATDFSMgmtConInstall
        {
            Ensure = "Present"
            Name   = "RSAT-DFS-Mgmt-Con"
        }

        WindowsFeature DFS
        {
            Name   = 'FS-DFS-Namespace'
            Ensure = 'Present'
        }

        xDFSNamespaceRoot DFSNamespaceRoot_Domain_Files
        {
            DependsOn  = @('[xSMBShare]DFSRootShare','[WindowsFeature]DFSFileServices')
            Path       = '\\ad.mydomain.us\Files'
            TargetPath = '\\dsc-test01.ad.mydomain.us\Files'
            Ensure     = 'present'
            Type       = 'DomainV2'
        } 
    }
}

$ConfigData = @{
    AllNodes = @(
        @{Nodename = 'dsc-test01'}
    )
}

DFSNamespace_Domain_SingleTarget -configurationData $ConfigData -OutputPath C:\dsc\DFS-Stuff\DFSNamespace_Domain_SingleTarget
Start-DscConfiguration -Wait -Force -Verbose -ComputerName 'dsc-test01' -Path C:\dsc\DFS-Stuff\DFSNamespace_Domain_SingleTarget
```

**Comment by PlagueHO** [comment]
Hi @joeypiccola, thank you for raising this issue.

In:

``` powershell
        xDFSNamespaceRoot DFSNamespaceRoot_Domain_Files
        {
            DependsOn  = @('[xSMBShare]DFSRootShare','[WindowsFeature]DFSFileServices')
            Path       = '\\ad.mydomain.us\Files'
            TargetPath = '\\dsc-test01.ad.mydomain.us\Files'
            Ensure     = 'present'
            Type       = 'DomainV2'
        } 
```

Can you try changing the TargetPath to:

``` powershell
TargetPath = '\\dsc-test01\Files'
```

However, if you'd prefer to use the full FQDN of the Targetpath, you can add a step to the config (before the `[xDFSNamespaceRoot]DFSNamespaceRoot_Domain_Files` step) that switches the DFSN to FQDN mode:

``` powershell
        xDFSNamespaceServerConfiguration DFSNamespaceConfig
        {
            IsSingleInstance          = 'Yes'
            UseFQDN                   = $true
            PsDscRunAsCredential      = $Credential
        } # End of xDFSNamespaceServerConfiguration Resource
```

I'm figuring out the best way of documenting this as this becomes an even bigger problem in Server 2016. See [this issue](https://github.com/PowerShell/xDFS/issues/21) for more info.

**Comment by joeypiccola** [comment]
@PlagueHO 

Changing the following did not work. 

``` Powershell
TargetPath = '\\dsc-test01\Files'
```

The following also did not work when used with "TargetPath = '\dsc-test01.ad.mydomain.com\Files'".

``` Powershell
xDFSNamespaceServerConfiguration DFSNamespaceConfig
{
    IsSingleInstance          = 'Yes'
    UseFQDN                   = $true
    PsDscRunAsCredential      = $Credential
} # End of xDFSNamespaceServerConfiguration Resource
```

Let me mess with this a bit, perhaps I don't understand the credentials piece (as I have removed them). I bet you that it's. Will report back in a bit. Thanks @PlagueHO 

Update: oh boy... just opened up a can of worms (e.g. securing a MOF file)...

**Comment by joeypiccola** [comment]
@PlagueHO 

Got it working! Dang, that was a fair amount of work. Basically, followed the instructions found on the following link to get credential encryption and decryption working with self-signed certs. Ended up submitting a PR too for the doc. https://msdn.microsoft.com/en-us/powershell/dsc/secureMOF 

As for the issue, to be honest I am not sure if having added the following fixed it. Both hostname and FQDN are working right now TargetPath. It's also possible that having run the below once already, made the changes required for FQDN to work. Thanks for the help! 

``` Powershell
xDFSNamespaceServerConfiguration DFSNamespaceConfig
{
    IsSingleInstance          = 'Yes'
    UseFQDN                   = $true
    PsDscRunAsCredential      = $Credential
} # End of xDFSNamespaceServerConfiguration Resource
```

-Joey

**Comment by PlagueHO** [comment]
@joeypiccola - good work getting it going! Secure MOF is something worthwhile getting a handle on anyway as it is something you'll run across at some stage with DSC.

However, I'm not actually sure if you needed the PsDscRunAsCredential parameter - you may have been able to use the `xDFSNamespaceServerConfiguration` resource without it. It will depend on how your DFS server is set up.

Is this now working for you? If so, can I close this one?

**Comment by joeypiccola** [comment]
@PlagueHO,

> can I close this one?

Yes!
