### ISSUE TITLE
Creating DFS Namespace and Replication Groups

### ISSUE THREAD

**Issue by oradcliffe** [dsccommunity/DFSDsc#24]
Hey guys,

Was hoping someone could point me in the right direction with this one - I am trying to use this in an Azure template, but right now am testing it on a couple local VMs.  My DSC script is the following:

<script src="https://gist.github.com/oradcliffe/ca09ad936639b42f9339817aeae627e4.js"></script>

The output I am getting, after the features are installed, is like this:

(Since it's a wall of text, basically a lot of these "PowerShell DSC resource MSFT_xDFSNamespaceRoot  failed to execute Set-TargetResource functionality with error message: A general error occurred that is not covered by a more specific error code.")

'Get-WindowsFeature' started: RSAT-DFS-Mgmt-Con
VERBOSE: [SERVERB]:                            [[WindowsFeature]RSATDFSMgmtConInstall] The operation
'Get-WindowsFeature' succeeded: RSAT-DFS-Mgmt-Con
VERBOSE: [SERVERB]: LCM:  [ End    Test     ]  [[WindowsFeature]RSATDFSMgmtConInstall]  in 0.2030 seconds.
VERBOSE: [SERVERB]: LCM:  [ Skip   Set      ]  [[WindowsFeature]RSATDFSMgmtConInstall]
VERBOSE: [SERVERB]: LCM:  [ End    Resource ]  [[WindowsFeature]RSATDFSMgmtConInstall]
VERBOSE: [SERVERB]: LCM:  [ Start  Resource ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01]
VERBOSE: [SERVERB]: LCM:  [ Start  Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01] Test-TargetResource:
Testing DomainV2 DFS Namespace Root "\\gametimeor.priv\Public" Target "\\GTM-FS01\Public".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01] Test-TargetResource:
DomainV2 DFS Namespace Root "\\gametimeor.priv\Public" does not exist but should. Change required.
VERBOSE: [SERVERB]: LCM:  [ End    Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01]  in 0.8750 seconds.
VERBOSE: [SERVERB]: LCM:  [ Start  Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01] Set-TargetResource:
Setting DomainV2 DFS Namespace Root "\\gametimeor.priv\Public" Target "\\GTM-FS01\Public".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01] Perfoming operation
"Create DFS Namespace" on Target "\\gametimeor.priv\Public"
VERBOSE: [SERVERB]: LCM:  [ End    Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS01]  in 2.5640 seconds.
PowerShell DSC resource MSFT_xDFSNamespaceRoot  failed to execute Set-TargetResource functionality with error message:
A general error occurred that is not covered by a more specific error code.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [SERVERB]: LCM:  [ Start  Resource ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02]
VERBOSE: [SERVERB]: LCM:  [ Start  Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02] Test-TargetResource:
Testing DomainV2 DFS Namespace Root "\\gametimeor.priv\Public" Target "\\GTM-FS02\Public".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02] Test-TargetResource:
DomainV2 DFS Namespace Root "\\gametimeor.priv\Public" does not exist but should. Change required.
VERBOSE: [SERVERB]: LCM:  [ End    Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02]  in 0.2180 seconds.
VERBOSE: [SERVERB]: LCM:  [ Start  Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02] Set-TargetResource:
Setting DomainV2 DFS Namespace Root "\\gametimeor.priv\Public" Target "\\GTM-FS02\Public".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02] Perfoming operation
"Create DFS Namespace" on Target "\\gametimeor.priv\Public"
VERBOSE: [SERVERB]: LCM:  [ End    Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Public_FS02]  in 2.5000 seconds.
PowerShell DSC resource MSFT_xDFSNamespaceRoot  failed to execute Set-TargetResource functionality with error message:
A general error occurred that is not covered by a more specific error code.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [SERVERB]: LCM:  [ Start  Resource ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01]
VERBOSE: [SERVERB]: LCM:  [ Start  Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01] Test-TargetResource:
Testing DomainV2 DFS Namespace Root "\\gametimeor.priv\Private" Target "\\GTM-FS01\Private".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01] Test-TargetResource:
DomainV2 DFS Namespace Root "\\gametimeor.priv\Private" does not exist but should. Change required.
VERBOSE: [SERVERB]: LCM:  [ End    Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01]  in 0.2030 seconds.
VERBOSE: [SERVERB]: LCM:  [ Start  Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01] Set-TargetResource:
Setting DomainV2 DFS Namespace Root "\\gametimeor.priv\Private" Target "\\GTM-FS01\Private".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01] Perfoming operation
"Create DFS Namespace" on Target "\\gametimeor.priv\Private"
VERBOSE: [SERVERB]: LCM:  [ End    Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS01]  in 0.1720 seconds.
PowerShell DSC resource MSFT_xDFSNamespaceRoot  failed to execute Set-TargetResource functionality with error message:
A general error occurred that is not covered by a more specific error code.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [SERVERB]: LCM:  [ Start  Resource ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02]
VERBOSE: [SERVERB]: LCM:  [ Start  Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02] Test-TargetResource:
Testing DomainV2 DFS Namespace Root "\\gametimeor.priv\Private" Target "\\GTM-FS02\Private".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02] Test-TargetResource:
DomainV2 DFS Namespace Root "\\gametimeor.priv\Private" does not exist but should. Change required.
VERBOSE: [SERVERB]: LCM:  [ End    Test     ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02]  in 0.1880 seconds.
VERBOSE: [SERVERB]: LCM:  [ Start  Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02]
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02] Set-TargetResource:
Setting DomainV2 DFS Namespace Root "\\gametimeor.priv\Private" Target "\\GTM-FS02\Private".
VERBOSE: [SERVERB]:                            [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02] Perfoming operation
"Create DFS Namespace" on Target "\\gametimeor.priv\Private"
VERBOSE: [SERVERB]: LCM:  [ End    Set      ]  [[xDFSNamespaceRoot]DFSNamespaceRoot_Private_FS02]  in 0.1560 seconds.
PowerShell DSC resource MSFT_xDFSNamespaceRoot  failed to execute Set-TargetResource functionality with error message:
A general error occurred that is not covered by a more specific error code.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [SERVERB]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 8.754 seconds

If there's anything that jumps out at you please let me know; I am not sure what to make of the general error.

Also, it doesn't seem like my gist is displaying properly, so my apologies there.

**Comment by PlagueHO** [comment]
Hi @oradcliffe - thanks for reporting this!

Is this being deployed to Windows Server 2016 or Windows Server 2012 R2 servers?

I ask because on Windows Server 2016 servers, DFS is configured slightly differently out of the box. Basically in Windows Server 2016 the DFS namespaces are not configured with a UseFQDN value set.

To fix this add a DSC config step at the beginning that sets the UseFQDN value to $false:

E.g.
```
xDFSNamespaceServerConfiguration DFSNamespaceConfig
{
       IsSingleInstance          = 'Yes'
       UseFQDN                   = $false
} # End of xDFSNamespaceServerConfiguration Resource

If the UseFQDN setting is not set then it defaults to null, which seems to cause problems. See this [discussion](https://github.com/PowerShell/xDFS/issues/15#issuecomment-255501893) for more detail on this.

Does that help? If not, then I'll dig further into this.

**Comment by oradcliffe** [comment]
Hi @PlagueHO, no I'm trying to deploy to 2012R2;I actually saw that thread last night trying to troubleshoot this.

**Comment by PlagueHO** [comment]
@oradcliffe - ok no worries. I'll dig deeper into your logs and get back to you (will try for tonight, but it might take a bit longer).

**Comment by oradcliffe** [comment]
No problem, thank you for your help.  I will keep working on it too and update here.  To be certain though, what I am trying to accomplish is doable right?  I have a Windows domain coming up, followed by two file servers, and on those I am trying to create a namespace for public and for different AD groups, and have those directories replicated across the two file servers, 1:1.  The xDFS github page says that namespaces aren't supported yet, but I thought I would try it out anyway.

**Comment by PlagueHO** [comment]
@oradcliffe - so far it looks like you're doing everything right.

Could you try executing the following cmdlet (setting the domain name) on your DFS node (the one the DSC Config is applying to) using the user Context that you're using to apply the DSC Config (e.g. $DomainCreds):
```powershell
$DomainName = 'Domain Name'
New-DfsnRoot `
    -Path "\\$DomainName\Public" `
    -TargetPath '\\GTM-FS01\Public' `
    -Type 'DomainV2'
```
Does this cmdlet succeed? It appears this is the cmdlet that is causing the exception to be thrown in the resource.

**Comment by oradcliffe** [comment]
@PlagueHO - this may be a dumb question, but should I be creating folders on both file shares and sharing them before this?  I know I could use the DSC File and xSMBShare resources for that, and I am testing that on local VMs.

**Comment by oradcliffe** [comment]
@PlagueHO Hey I have been working on this a bunch, and I think what you proposed using the xDFSNamespaceServerConfiguration may have quelled some undefined errors, but I have changed so much at this point it would be hard to say.  I could remove it from what I have working now and I suppose tell that way.

What I wound up doing was using the File, xSMBShare, and cNtfsAccessControl modules on the first file server and creating the directories locally there with appropriate sharing and NTFS permissions.  Then on the other server, I have some code to join it to the domain, create those directories and shares, then create the namespaces and replication groups.

Initially, I was going to have a \\domain\public, \\domain\private, \\domain\private\somegroup, and a few other similar ones based on group membership in AD, but having the duplicate \private then \private\group seemed to be problematic, so I reduced that down to \public and \group1, \group2 etc.  That all seems to work on a little local AD domain I have in VMWare Workstation, so I will try to work this into my Azure deployment template soon.

If you're interested in seeing what I got working, I am using the second two zips on https://github.com/oradcliffe/localADConfig for configuring the two local (I just mean not in azure) file servers.  If you have any tips for me that would be great, like I am still not totally sure if I have to go to all that trouble setting up the shares, but I am glad I did anyway because realistically you wouldn't be setting things up with share permissions alone.

**Comment by PlagueHO** [comment]
HI @oradcliffe - oh yes, the SMB Shares need to already exist. I didn't even think to confirm this with you. This behavior is expected because that is how the DFSN PowerShell cmdlets work. This is different to the DFSN Server GUI console - which creates the SMB shares for you. So I understand where the confusion comes from.

I think there is three things that I could do here:
1. Update the documentation to make it clear that this is expected.
2. Improve the examples to indicate that the SMB shares are expected to exist.
3. Possibly add some tests in the Set-TargetResource of the DFSN resources that confirm the SMB shares exist. The problem with this though might be that the SMB shares might not be accessible using the credentials that the DSC config is being applied using. I'll need to think about this.

Your configs look pretty good. I tend to avoid putting all my Import-DSCResources on one line, but that is only because I've got some automation that identifies the DSC Resource Modules required and ensures they're automatically installed or deployed to my pull servers.

Anyway, good work! Glad you're making progress!

**Comment by oradcliffe** [comment]
Hey!  I also got it all working deploying to Azure as well, so if you'd like to take a look at that it's on my DFS branch, but will be merging into master today.  I did encounter one additional undefined error when I was refactoring everything to work with Azure - in xDFSNamespaceRoot, if the TargetPath doesn't exist (like if you typo a server name - \\servera\Public instead of \\server-a\Public for example - you're met with a general error.  Going through resource by resource it was a pretty easy mistake to troubleshoot, but it might be worth putting something there.  Otherwise, thanks for your help!

**Comment by oradcliffe** [comment]
@PlagueHO Hey, it's merged into the master branch and works perfectly.  Just wanted to say thank you again!

**Comment by PlagueHO** [comment]
@oradcliffe - that is great to hear and really inspiring that you're showing the usage of this up in the cloud. Always a pleasure to help.

Can I close this one?

**Comment by oradcliffe** [comment]
@PlagueHO - Thanks for the kind words!  You can definitely close this one and thanks so much again for your help.  Happy holidays!

**Comment by PlagueHO** [comment]
@oradcliffe - you too! Cheers sir!

**Comment by oradcliffe** [comment]
@PlagueHO  - Have been looking at [this](https://dscottraynsford.wordpress.com/2016/10/04/easily-create-a-hyper-v-windows-server-2016-ad-nano-server-lab/) the last few days in anticipation of a new server I am setting up at home, and didn't realize it was yours!  Very cool!

**Comment by PlagueHO** [comment]
Haha @oradcliffe - good spotting. I actually created Labbuilder as an easy way to spin up and test the DSC resources I was creating (e.g. this one, FSRMDsc, WSManDsc and iSCSIDsc). And eventually it ended up how it is now. I haven't been giving it much love lately though - too much on. But if you find anything that needs changing, let me kmow!
