### ISSUE TITLE
xDFSNamespaceRoot:  failed to execute Set-TargetResource functionality with error message: Operation ca not be carried out because an object already exists

### ISSUE THREAD

**Issue by riccardin** [dsccommunity/DFSDsc#54]
I'm creating DFS namespaces and replications groups via puppet in 2 servers.

The snippet puppet code looks  something like:

create_resources(**dsc_xdfsnamespaceroot**, $cfg[namespaces], $credential)

The namespaces is a hash which looks something like:
**namespaces:
     folderName:
       dsc_ensure: 'present'
       dsc_path: "\\\\%{::networking.domain}\\folderName"
       dsc_targetpath: "\\\\%{::hostname}\\folderName"
       dsc_description: 'Repository for ISOs and packages'
       dsc_type: 'DomainV2'**

Everything works fine the DFS gets created as expected in both Servers. But once the DFS is created and I need to run puppet again on the secondary server I'm getting next error:

_Error: PowerShell DSC resource MSFT_xDFSNamespaceRoot  failed to execute Set-TargetResource functionality with error mesage: Operation cannot be carried out because an object already exists.
rror: /Stage[main]/Profile::Dfs/Dsc_xdfsnamespaceroot[folderName]/ensure: change from absent to present failed: PowerShellSC resource MSFT_xDFSNamespaceRoot  failed to execute Set-TargetResource functionality with error message: Operation canot be carried out because an object already exists._

This is running in a Windows Server 2016
PowerShell 5,1

is the xDFSNameSpaceFolder module really idempotent ? or do I missing something?

**Comment by PlagueHO** [comment]
Hi @riccardin - thanks for submitting this.

I suspect this is actually related to https://github.com/PowerShell/xDFS/issues/15 .

The best way to resolve this is to use FQDN for the dsc_targetpath hostname and use the `xDFSNamespaceServerConfiguration` resource to configure `UseFQDN` to be `$true`.

e.g.
```powershell
        xDFSNamespaceServerConfiguration DFSNamespaceConfig
        {
            IsSingleInstance          = 'Yes'
            UseFQDN                   = $true
            PsDscRunAsCredential      = $Credential
        } #
```

The reason for this is that in Windows Server 2016 the host name can be set as a NetBIOS name, but DFS will return it as an FQDN. This causes the DFS resource to think the namespace doesn't exist. But forcing the use of FQDN everywhere usually solves the problem.

Could you give this a try and let me know if it works?

**Comment by riccardin** [comment]
Thanks @PlagueHO! for your prompt response.  I'm going to give a try and let you know

**Comment by riccardin** [comment]
Hi @PlagueHO I applied the suggested changes but I'm still getting the same error.  I have tried setting Fqdn either to True and False and nothing looks to work.

![image](https://user-images.githubusercontent.com/1487507/32971120-a767be00-cba0-11e7-892c-42e5373ce397.png)

**Comment by PlagueHO** [comment]
:cry: Back to the drawing board!

I'm not super experienced with using Chef, but is it possible to get Chef to apply the DSC resource using the -Verbose parameter? This will output a bunch more logs I can look at.

And just to confirm, the `::hostname` in `dsc_targetpath: "\\%{::hostname}\folderName"` is putting the FQDN of the machine into the `dsc_targetpath`?

E.g.
\\myserver.contoso.com\folderName

Rather than
\\myserver\folderName

But if you can get me the Verbose logs that would be most helpful too :grin: Thanks for helping me solve this!

**Comment by riccardin** [comment]
I can see it is setting the  dsc_targetpath  as  '\myserver\folderName'  the dsc_path is set as '\myserver.contoso.com\folderName'.

Also, I just noticed that the module version installed is 3.1.0.0.  Does the version 3.2.0.0 address this issue?  

Sure I can provide the Verbose logs if needed. And no worries I'm happy to contribute to whatever I can.

**Comment by PlagueHO** [comment]
@riccardin - thanks for that. I actually see one problem here:
The `dsc_path` should not contain a server name in it. It should just contain the domain (for a DomainV2 type NS). E.g.
dsc_path = '\\\\contoso.com\folderName'
dsc_targetpath = '\\\\myserver.contoso.com\folderName'

Take a look at this example 1 on this page https://github.com/PowerShell/xDFS/wiki/xDFSNamespaceRoot

Ignore Examples 3 and 4 as they're for non-domain Namespaces. Unfortunately the examples are not using FQDN for the target names but you'll want to use FQDN if you're using WS 2016.

**Comment by riccardin** [comment]
Thanks, @PlagueHO.  Finally, it is working.  To summarize were two issues.

1. FQDN was null so it has to be set.
2. dsc_targetpath  was wrong.  It was missing the domain.
