### ISSUE TITLE
xDFSReplicationMembership - add support for modifying staging quota

### ISSUE THREAD

**Issue by murrahjm** [dsccommunity/DFSDsc#77]
#### Details of the scenario you tried and the problem that is occurring
When creating or modifying a DFS replication group membership, the staging quota size is left at the default of 4gb
#### Suggested solution to the issue
Add parameter to the xDFSReplicationGroup to allow setting the staging quota size
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        DFSReplicationGroupMembership RGWebSiteMembershipHub
        {
            GroupName = 'WebSite'
            FolderName = 'WebSiteFiles'
            ComputerName = $HubComputerName
            ContentPath = 'd:\inetpub\wwwroot\WebSiteFiles'
            StagingPathQuotaInMB = 81960 # Proposed new parameter
            PrimaryMember = $true
            PSDSCRunAsCredential = $Credential
            DependsOn = '[DFSReplicationGroupFolder]RGWebSiteFolder'
        } # End of RGWebSiteMembershipHub Resource

```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1709
WindowsBuildLabEx    : 16299.431.amd64fre.rs3_release_svc_escrow.180502-1908
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.16299.611
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.611
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
'dev'

**Comment by PlagueHO** [comment]
Awesome idea - thanks for raising this @murrahjm. I've tagged this as help wanted. I've got a bit of a long backlog but I'll try and get to this as soon as I have time.
