### ISSUE TITLE
using cached auth for DFS updates

### ISSUE THREAD

**Issue by n3snah** [dsccommunity/DFSDsc#81]
When running this module, does it support/use cached auth rather than talking with AD against each namespace and/or folder check that it does?

**Comment by PlagueHO** [comment]
Hi @laywah2016 - that is a good question. However, I'm not sure of the answer as this resource just uses the [DFSR](https://docs.microsoft.com/en-us/powershell/module/dfsr/?view=win10-ps) and [DFSN](https://docs.microsoft.com/en-us/powershell/module/dfsn/?view=win10-ps) PowerShell modules that come with the OS. So it will completely depend on the behavior of those modules (which are not available as open source as far as I know).

**Comment by n3snah** [comment]
As far as I can see, there is no way to use a cached credential as the main DFSR and DFSN cmdlets don't seem to have that feature. The problem I face and why I asked the question is that we have a few namespaces which have a total of more than 5000 folder & targets and it takes an extremely long time to auth and just check them.

**Comment by PlagueHO** [comment]
That is a tough one indeed. You are right- the DFSR and DFSN cmdlets don't seem to support this. Even if they did though, it isn't clear if we could make each resource in a config "share" these credentials.

Out of interest, how long does it take to auth against the AD for these 5000 folders & targets? Is the domain controller that is being used to auth on a "close" network subnet? In theory, you could optimize this by placing a DC close to (or even on) the DFS nodes and forcing the auth to take place against them. However, if you've got a large AD database then you'd need a fair amount of horsepower on the DFS nodes to actually optimize the LDAP lookups. Just an idea though.

**Comment by n3snah** [comment]
it takes over 1 hour for a run. AD is within the same datacentre so its <1ms ping. This is also on a largish enterprise which spans Australia.
DFS doesn't seem to have many changes made since 2008 R2 except for the introduction of the cmdlets.

whats the likely hood of Microsoft doing further development around DFS and possibly introducing some kind of caching on the cmdlets? though our AD infrastructure is quite well resourced. this does increase the number of requests against the DCs by the thousands.

**Comment by PlagueHO** [comment]
Sorry for not getting back to you sooner, but I don't know what the likelihood of this sort of improvement being made is. It does sound like it could be something that could be looked at. Have you raised the issue over on User Voice? They might actually have some suggestions, even if the issue doesn't get fixed.

**Comment by gaelcolas** [comment]
@PlagueHO: Would it even work in DSC? I mean each resource is running in its own thread without communications/variable sharing with other resource instances, so if you mean some caching on the client side, then it'd have to be to disk... Which is probably not what you want.

**Comment by PlagueHO** [comment]
@gaelcolas - I think you are probably right here. Any kind of caching would of this sort of thing would have to be done at the DFS system layer - above PowerShell and above DSC. I can't see any way that we could implement it at the PowerShell/DSC layer.

**Comment by gaelcolas** [comment]
@laywah2016 I'm afraid there's not much that can be done here.
What I'd recommend if that's taking too long is to either:
- distribute that configuration against several servers (say, 1 server checks ~ 1000 folder & targets, so ~ 5 servers). 
- create your own resource that is optimised for speed (maybe wrapping around the Get/set/test of the existing resource, so that everything is done as the same user in the same runspace avoiding the cost of creating/destroying those 5k runspaces...

As this is out of scope for the DSC resources, I'm going to close this issue off. Feel free to hit me up (powershell slack/twitter/PowerShell.org DSC forums) if you want to discuss further.
